apiVersion: v1
kind: Pod
metadata:
  name: shankar-gs-gs
  labels:
    app: shankar-gs-gs
spec:
  containers:
  - name: shankar-gsgoud
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar-gs-gs
  namespace: default
spec:
  type: NodePort
  selector:
    app: shankar-gs-gs
  ports:
  - nodePort: 32501
    protocol: http
    targetPort: 8080
    port: 80 
