apiVersion: v1
kind: Pod
metadata:
  name: shankar-pod
  labels:
    app: shankargajula
spec:
  containers:
  - name: shankar-container
    image: "dockerawsdevops1/docker-private-repo:latest"
  imagePullSecrets:
  - name: smily
    
---
apiVersion: v1
kind: Service
metadata:
  name: shankar-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: shankargajula
  ports:
  - nodePort: 32503
    protocol: TCP
    targetPort: 8080
    port: 80 
